import XCTest
@testable import ArtWindowKit

final class ArtistsTests: XCTestCase {
    private let directory = URL(fileURLWithPath: "/tmp/artists")

    private func row(
        _ name: String, _ region: String = "EUROPE", byline: String? = nil, title: String = "A painting",
        file: String = "a.jpg"
    ) -> String {
        [name, region, "https://en.wikipedia.org/wiki/X", "1", title, byline ?? "\(name), 1889", file]
            .joined(separator: "\t")
    }

    private func artists(_ rows: String...) -> Artists {
        Artists(tsv: (["# Generated by test"] + rows).joined(separator: "\n"), directory: directory)
    }

    func testParsingSkipsShortRowsAndUnknownRegions() {
        let a = artists(
            row("Tom Roberts", "OCEANIA"),
            "Short\tOCEANIA\thttps://x\t1",
            row("Nowhere", "MARS"))
        XCTAssertEqual(a.painters.map(\.name), ["Tom Roberts"])
        XCTAssertEqual(a.painters[0].region, .oceania)
        XCTAssertEqual(a.painters[0].imageURL, directory.appendingPathComponent("a.jpg"))
    }

    func testCaptionStripsThePainterFromTheBylineToGetTheYear() {
        let a = artists(
            row("Arthur Streeton", "OCEANIA", byline: "Arthur Streeton, 1889", title: "Golden summer, Eaglemont"),
            row("No Year", byline: "No Year"))
        XCTAssertEqual(a.painters[0].year, "1889")
        XCTAssertEqual(
            a.painters[0].caption(paintings: 40), "Golden summer, Eaglemont, 1889 · Oceania, 40 paintings")
        XCTAssertNil(a.painters[1].year)
        XCTAssertEqual(a.painters[1].caption(paintings: 1), "A painting · Europe, 1 painting")
    }

    func testShelfIsByRegionThenNameAndOmitsPaintersNotInTheCatalogue() {
        let a = artists(
            row("Zed", "OCEANIA"), row("Bea", "SOUTH_AMERICA"), row("Ann", "SOUTH_AMERICA"),
            row("Eve", "EUROPE"), row("Gone", "EUROPE"))
        XCTAssertEqual(a.shelf(of: ["Zed", "Bea", "Ann", "Eve", "Unlisted"]).map(\.name), ["Eve", "Ann", "Bea", "Zed"])
    }

    func testPaintingsByCountsOnlyThatPaintersNonPortraits() {
        func line(_ id: String, _ title: String, _ artist: String) -> String {
            ["wmc", id, "EUROPE", "1000", "800", "https://x/\(id).jpg", "", title, "1800", "", "", artist]
                .joined(separator: "\t")
        }
        let c = Catalogue(tsv: [
            line("1", "River", "Ann"), line("2", "Portrait of a man", "Ann"),
            line("3", "Field", "Ann"), line("4", "Sea", "Bea"),
        ].joined(separator: "\n"))
        XCTAssertEqual(c.paintings(by: "Ann"), 2)
        XCTAssertEqual(c.paintings(by: "Bea"), 1)
        XCTAssertEqual(c.paintings(by: "Nobody"), 0)
    }
}

final class ArtistWinsAndRotationTests: XCTestCase {
    private let phone = Screen(width: 1000, height: 2000)
    private let ipad = Screen(width: 2000, height: 2000)

    private func line(
        _ id: String, region: String = "OCEANIA", title: String = "Field", width: Int = 4000, height: Int = 2000,
        artist: String? = nil
    ) -> String {
        var f = ["wmc", id, region, "\(width)", "\(height)", "https://x/\(id).jpg", "", title, "1800", "", "river"]
        if let artist { f.append(artist) }
        return f.joined(separator: "\t")
    }

    private func filters(
        shape: ArtworkShape = .screen, regions: Set<Region> = [.europe], subjects: Set<ArtworkSubject> = [],
        artists: Set<String> = [], hideReligious: Bool = false
    ) -> Filters {
        Filters(shape: shape, regions: regions, subjects: subjects, artists: artists, hideReligious: hideReligious)
    }

    func testAChosenPainterPassesWhateverTheRegionAndShape() {
        // Wide, from Oceania, on a phone set to screen-shaped Europe: only the painter admits it.
        let c = Catalogue(tsv: [line("1", artist: "Ann"), line("2", region: "EUROPE", artist: "Bea")].joined(separator: "\n"))
        let style = RenderStyle.defaults
        XCTAssertTrue(c.matching(filters(), screen: phone, style: style).isEmpty)
        XCTAssertEqual(c.matching(filters(artists: ["Ann"]), screen: phone, style: style).map(\.objectId), ["1"])
        XCTAssertEqual(c.availableArtists(filters(), screen: phone, style: style), ["Ann", "Bea"])
    }

    func testOnePaintingIsEnoughWithAPainterAndNineteenIsNotWithout() {
        let rows = (0..<19).map { line("\($0)", region: "EUROPE", width: 2000, height: 4000, artist: "Ann") }
        let c = Catalogue(tsv: rows.joined(separator: "\n"))
        XCTAssertEqual(Catalogue.needed(for: filters()), Catalogue.minPool)
        XCTAssertEqual(Catalogue.needed(for: filters(artists: ["Ann"])), 1)
        XCTAssertFalse(c.hasEnough(filters(), screen: phone))
        XCTAssertTrue(c.hasEnough(filters(artists: ["Ann"]), screen: phone))
    }

    func testWidenedLeavesAPainterAloneAndRelaxesSubjectsWhenTheyEmptyIt() {
        let c = Catalogue(tsv: line("1", title: "Field", artist: "Ann"))
        let kept = filters(artists: ["Ann"])
        XCTAssertEqual(c.widened(kept, screen: phone), kept)
        // Subject "seascape" matches nothing of Ann's: the subject goes, the painter stays.
        let narrowed = filters(subjects: [.seascape], artists: ["Ann"])
        XCTAssertEqual(c.widened(narrowed, screen: phone).subjects, [])
        XCTAssertEqual(c.widened(narrowed, screen: phone).artists, ["Ann"])
        XCTAssertEqual(c.whatEmpties("Ann", narrowed, screen: phone), .subject)
        XCTAssertNil(c.whatEmpties("Ann", kept, screen: phone))
    }

    func testHungSizeTurnsOnlyAWidePaintingOnATallScreenWhenAsked() {
        let on = RenderStyle(rotateWide: true)
        XCTAssertTrue(on.hung(width: 400, height: 200, on: phone) == (200, 400))
        XCTAssertTrue(on.hung(width: 200, height: 400, on: phone) == (200, 400))
        XCTAssertTrue(on.hung(width: 400, height: 200, on: ipad) == (400, 200))
        XCTAssertTrue(RenderStyle.defaults.hung(width: 400, height: 200, on: phone) == (400, 200))
    }

    func testCanRenderAndTheShapeFilterJudgeThePaintingAsHung() {
        // 2000x1000 is too small to zoom onto 1000x2000 unturned (needs 2000 tall); turned it is exact.
        XCTAssertFalse(RenderStyle.defaults.canRender(width: 2000, height: 1000, on: phone))
        XCTAssertTrue(RenderStyle(rotateWide: true).canRender(width: 2000, height: 1000, on: phone))
        let c = Catalogue(tsv: line("1", width: 4000, height: 2000))
        let f = filters(regions: [])
        XCTAssertTrue(c.matching(f, screen: phone, style: .defaults).isEmpty)
        XCTAssertEqual(c.matching(f, screen: phone, style: RenderStyle(rotateWide: true)).count, 1)
    }

    func testAStyleSavedWithoutRotateWideStillDecodes() throws {
        let json = #"{"mode":"blur","blurStrength":70,"blurWholeFill":true,"border":{"black":{}}}"#
        let style = try JSONDecoder().decode(RenderStyle.self, from: Data(json.utf8))
        XCTAssertEqual(style.mode, .blur)
        XCTAssertEqual(style.blurStrength, 70)
        XCTAssertFalse(style.rotateWide)
        let round = try JSONDecoder().decode(RenderStyle.self, from: JSONEncoder().encode(RenderStyle(rotateWide: true)))
        XCTAssertTrue(round.rotateWide)
    }
}

final class FramingTests: XCTestCase {
    private let phone = Screen(width: 1000, height: 2000)
    private let wide = CGSize(width: 4000, height: 2000)
    private var screen: CGSize { CGSize(width: 1000, height: 2000) }

    func testZoomOneCentredIsTodaysCoverAndFit() throws {
        let cover = Framing.rect(painting: wide, screen: screen, base: .cover)
        let placement = try XCTUnwrap(phone.cover(width: 4000, height: 2000))
        XCTAssertEqual(cover.width, CGFloat(placement.scaledWidth), accuracy: 1)
        XCTAssertEqual(cover.minX, -CGFloat(placement.crop.left), accuracy: 1)
        XCTAssertEqual(cover.minY, 0, accuracy: 0.01)
        let fit = Framing.rect(painting: wide, screen: screen, base: .fit)
        let fitted = try XCTUnwrap(phone.fit(width: 4000, height: 2000))
        XCTAssertEqual(fit.width, CGFloat(fitted.scaledWidth), accuracy: 1)
        XCTAssertEqual(fit.minY, CGFloat(fitted.destination.top), accuracy: 1)
    }

    func testZoomedFitOverflowsBothAxesAndPanPutsItAtEachEdge() {
        // A 1000x2000 painting fitted into 1000x1500 is 750 wide; at zoom 2 it is 1500x3000 and overflows both ways.
        let z = Framing.rect(painting: CGSize(width: 1000, height: 2000), screen: CGSize(width: 1000, height: 1500), base: .fit, zoom: 2, panX: 0, panY: 0)
        XCTAssertEqual(z.width, 1500, accuracy: 0.01)
        XCTAssertEqual(z.height, 3000, accuracy: 0.01)
        XCTAssertEqual(z.minX, 0, accuracy: 0.01)
        XCTAssertEqual(z.minY, 0, accuracy: 0.01)
        let far = Framing.rect(painting: CGSize(width: 1000, height: 2000), screen: CGSize(width: 1000, height: 1500), base: .fit, zoom: 2, panX: 1, panY: 1)
        XCTAssertEqual(far.maxX, 1000, accuracy: 0.01)
        XCTAssertEqual(far.maxY, 1500, accuracy: 0.01)
        let mid = Framing.rect(painting: CGSize(width: 1000, height: 2000), screen: CGSize(width: 1000, height: 1500), base: .fit, zoom: 2)
        XCTAssertEqual(mid.midX, 500, accuracy: 0.01)
        XCTAssertEqual(mid.midY, 750, accuracy: 0.01)
    }

    func testPanOnAnAxisThatDoesNotOverflowHasNoEffectAndOverflowAlwaysCovers() {
        let a = Framing.rect(painting: wide, screen: screen, base: .cover, panX: 0.5, panY: 0)
        let b = Framing.rect(painting: wide, screen: screen, base: .cover, panX: 0.5, panY: 1)
        XCTAssertEqual(a, b)
        for pan in [0.0, 0.3, 1.0, 5.0, -2.0] {
            let r = Framing.rect(painting: wide, screen: screen, base: .cover, zoom: 2.5, panX: pan, panY: pan)
            XCTAssertLessThanOrEqual(r.minX, 0.001)
            XCTAssertGreaterThanOrEqual(r.maxX, screen.width - 0.001)
            XCTAssertLessThanOrEqual(r.minY, 0.001)
            XCTAssertGreaterThanOrEqual(r.maxY, screen.height - 0.001)
        }
    }

    func testPreviewAndScreenAgreeUpToTheScale() {
        let big = Framing.rect(painting: wide, screen: screen, base: .fit, zoom: 2.2, panX: 0.2, panY: 0.7)
        let small = Framing.rect(painting: wide, screen: CGSize(width: 100, height: 200), base: .fit, zoom: 2.2, panX: 0.2, panY: 0.7)
        XCTAssertEqual(big.minX / 10, small.minX, accuracy: 0.01)
        XCTAssertEqual(big.minY / 10, small.minY, accuracy: 0.01)
        XCTAssertEqual(big.width / 10, small.width, accuracy: 0.01)
        XCTAssertEqual(big.height / 10, small.height, accuracy: 0.01)
    }

    func testPanBelongsToOnePaintingButZoomOutlivesIt() {
        let style = RenderStyle(frameZoom: 2, panX: 0.2, panY: 0.9, panFor: "a.jpg")
        XCTAssertTrue(style.effectivePan(for: "a.jpg") == (0.2, 0.9))
        XCTAssertTrue(style.effectivePan(for: "b.jpg") == (0.5, 0.5))
        XCTAssertEqual(style.effectiveZoom, 2)
        XCTAssertEqual(RenderStyle(frameZoom: 9).effectiveZoom, 3)
    }

    func testWhichStylesAndScreensCanBeFramed() {
        XCTAssertTrue(RenderStyle(mode: .zoom).canFrame(on: phone))
        XCTAssertTrue(RenderStyle(mode: .borders).canFrame(on: phone))
        XCTAssertTrue(RenderStyle(mode: .blur).canFrame(on: phone))
        XCTAssertFalse(RenderStyle(mode: .blur, blurWholeFill: true).canFrame(on: phone))
        XCTAssertFalse(RenderStyle(mode: .stretch).canFrame(on: phone))
        XCTAssertFalse(RenderStyle(mode: .zoom).canFrame(on: Screen(width: 2000, height: 2000)))
        // A turned painting is framed like any other.
        XCTAssertTrue(RenderStyle(rotateWide: true).canFrame(on: phone))
    }

    func testRectIsCentredWhenTheStyleCannotFrame() {
        let style = RenderStyle(mode: .stretch, frameZoom: 3, panX: 0, panY: 0, panFor: "a.jpg")
        let r = style.framedRect(for: "a.jpg", painting: wide, on: phone)
        XCTAssertEqual(r, Framing.rect(painting: wide, screen: screen, base: .fit))
    }

    func testAStyleSavedBeforeFramingOrWithTheOldSinglePanStillDecodes() throws {
        let before = #"{"mode":"zoom","blurStrength":50,"blurWholeFill":false,"border":{"black":{}},"rotateWide":true}"#
        var style = try JSONDecoder().decode(RenderStyle.self, from: Data(before.utf8))
        XCTAssertEqual(style.frameZoom, 1)
        XCTAssertEqual(style.panX, 0.5)
        XCTAssertNil(style.panFor)
        let old = #"{"mode":"zoom","blurStrength":50,"blurWholeFill":false,"border":{"black":{}},"pan":0.1,"panFor":"x.jpg"}"#
        style = try JSONDecoder().decode(RenderStyle.self, from: Data(old.utf8))
        XCTAssertEqual(style.panX, 0.1)
        XCTAssertEqual(style.panY, 0.1)
        XCTAssertEqual(style.panFor, "x.jpg")
        let round = try JSONDecoder().decode(
            RenderStyle.self, from: JSONEncoder().encode(RenderStyle(rotateWide: true, frameZoom: 2.5, panX: 0.3, panY: 0.8, panFor: "y")))
        XCTAssertEqual(round, RenderStyle(rotateWide: true, frameZoom: 2.5, panX: 0.3, panY: 0.8, panFor: "y"))
    }

    func testChoosingAPainterReplacesWhoeverWasChosenAndAnyClears() {
        var f = Filters(artists: ["Ann"])
        f.chooseArtist("Bea")
        XCTAssertEqual(f.artists, ["Bea"])
        f.anyArtist()
        XCTAssertTrue(f.artists.isEmpty)
    }

    func testStoredSeveralPaintersReadAsOneOnly() throws {
        let json = """
        {"shape":"screen","regions":[],"subjects":[],"artists":["Cy","Ann","Bea"],"hideReligious":false}
        """
        let f = try JSONDecoder().decode(Filters.self, from: Data(json.utf8))
        XCTAssertEqual(f.artists, ["Ann"])
    }
}
