import XCTest
@testable import ArtWindowKit

final class CatalogueTests: XCTestCase {
    private let screen = Screen(width: 1000, height: 2000)
    private let style = RenderStyle.defaults

    private func row(
        _ source: String, _ id: String, _ region: String, title: String, tags: String = "",
        width: Int = 1000, height: Int = 2000, artist: String? = nil
    ) -> String {
        var fields = [
            source, id, region, "\(width)", "\(height)", "https://example.org/\(id).jpg",
            "https://example.org/art/\(id)", title, "1800", "Somewhere", tags,
        ]
        if let artist { fields.append(artist) }
        return fields.joined(separator: "\t")
    }

    private func catalogue(_ rows: String...) -> Catalogue {
        Catalogue(tsv: (["# Generated by test"] + rows).joined(separator: "\n"))
    }

    private func filters(
        shape: ArtworkShape = .any, regions: Set<Region> = [], subjects: Set<ArtworkSubject> = [],
        artists: Set<String> = [], hideReligious: Bool = false
    ) -> Filters {
        Filters(shape: shape, regions: regions, subjects: subjects, artists: artists, hideReligious: hideReligious)
    }

    private func ids(_ c: Catalogue, _ f: Filters) -> Set<String> {
        Set(c.matching(f, screen: screen, style: style).map(\.objectId))
    }

    func testParsingSkipsBadRowsAndReadsOptionalArtist() {
        let c = catalogue(
            row("met", "1", "EUROPE", title: "A"),
            row("wmc", "2", "ASIA", title: "B", artist: "Hokusai"),
            row("xxx", "3", "EUROPE", title: "unknown source"),
            row("met", "4", "MARS", title: "unknown region"),
            "met\t5\tEUROPE\t0\t10\thttps://x\t\tzero width\t\t\t",
            "too\tfew"
        )
        XCTAssertEqual(c.entries.map(\.objectId), ["1", "2"])
        XCTAssertNil(c.entries[0].artist)
        XCTAssertEqual(c.entries[1].artist, "Hokusai")
        XCTAssertEqual(c.entries[1].id, "wmc-2")
    }

    func testSectionsAreAndedOptionsAreOred() {
        let c = catalogue(
            row("met", "eu-land", "EUROPE", title: "Landscape with Trees"),
            row("met", "as-land", "ASIA", title: "Landscape at Dusk"),
            row("met", "eu-sea", "EUROPE", title: "A Seascape"),
            row("met", "as-sea", "ASIA", title: "Seascape"),
            row("met", "af-still", "AFRICA", title: "Still Life with Flowers")
        )
        XCTAssertEqual(ids(c, filters(regions: [.europe], subjects: [.landscape])), ["eu-land"])
        XCTAssertEqual(ids(c, filters(regions: [.europe, .asia], subjects: [.landscape])), ["eu-land", "as-land"])
        XCTAssertEqual(ids(c, filters(regions: [.europe], subjects: [.landscape, .seascape])), ["eu-land", "eu-sea"])
    }

    func testEmptySectionMeansAny() {
        let c = catalogue(
            row("met", "1", "EUROPE", title: "Landscape"),
            row("met", "2", "AFRICA", title: "Untitled mask")
        )
        XCTAssertEqual(ids(c, filters()), ["1", "2"])
        XCTAssertEqual(ids(c, filters(regions: [.africa])), ["2"])
    }

    func testSubjectMatchesWholeWordsPluralsAndTags() {
        let c = catalogue(
            row("met", "plural", "EUROPE", title: "Boats at Rest"),
            row("met", "tag", "EUROPE", title: "Untitled", tags: "Flowers|Vases"),
            row("met", "embedded", "EUROPE", title: "Streetcar"),
            row("met", "space", "EUROPE", title: "Still Life")
        )
        XCTAssertEqual(ids(c, filters(subjects: [.seascape])), ["plural"])
        XCTAssertEqual(ids(c, filters(subjects: [.stillLife])), ["tag", "space"])
        XCTAssertEqual(ids(c, filters(subjects: [.landscape])), [], "\"street\" must not match inside \"Streetcar\"")
    }

    func testDanishWordsMatchSMKTitles() {
        let c = catalogue(
            row("smk", "1", "EUROPE", title: "Landskab med træer"),
            row("smk", "2", "EUROPE", title: "Udsigt over havnen"),
            row("smk", "3", "EUROPE", title: "Skibe ved kysten"),
            row("smk", "4", "EUROPE", title: "Opstilling med blomster"),
            row("smk", "5", "EUROPE", title: "En mand by night")
        )
        XCTAssertEqual(ids(c, filters(subjects: [.landscape])), ["1", "2"])
        XCTAssertEqual(ids(c, filters(subjects: [.seascape])), ["3"])
        XCTAssertEqual(ids(c, filters(subjects: [.stillLife])), ["4"])
    }

    func testChristmasIsNotChrist() {
        let c = catalogue(
            row("met", "xmas", "EUROPE", title: "Christmas Market"),
            row("met", "christ", "EUROPE", title: "Christ in Glory"),
            row("met", "tag", "EUROPE", title: "Untitled", tags: "Virgin Mary"),
            row("met", "danish", "EUROPE", title: "Kristus på korset"),
            row("met", "petersburg", "EUROPE", title: "View of St. Petersburg"),
            row("met", "holy", "EUROPE", title: "Wholly Owned")
        )
        XCTAssertEqual(ids(c, filters(hideReligious: true)), ["xmas", "petersburg", "holy"])
        XCTAssertEqual(ids(c, filters(hideReligious: false)).count, 6)
    }

    func testPortraitsAreAlwaysExcluded() {
        let c = catalogue(
            row("met", "title", "EUROPE", title: "Portrait of a Man"),
            row("met", "tag", "EUROPE", title: "Man in Red", tags: "Portraits"),
            row("smk", "danish", "EUROPE", title: "Portræt af en kvinde"),
            row("met", "ok", "EUROPE", title: "Landscape")
        )
        XCTAssertEqual(ids(c, filters(subjects: [])), ["ok"])
    }

    func testShapeAndRenderabilityGateEntries() {
        let c = catalogue(
            row("met", "tall", "EUROPE", title: "Tall", width: 1000, height: 2000),
            row("met", "wide", "EUROPE", title: "Wide", width: 2000, height: 1000),
            row("met", "tiny", "EUROPE", title: "Tiny", width: 500, height: 1000)
        )
        XCTAssertEqual(ids(c, filters(shape: .screen)), ["tall"])
        // Zoom must cover the screen: "wide" would be enlarged 2x, "tiny" 2x.
        XCTAssertEqual(ids(c, filters(shape: .any)), ["tall"])
        // Fit-style renders enlarge by the smaller factor, so "wide" now qualifies; "tiny" still needs 2x.
        let borders = RenderStyle(mode: .borders)
        XCTAssertEqual(Set(c.matching(filters(), screen: screen, style: borders).map(\.objectId)), ["tall", "wide"])
    }

    func testAvailabilityHoldsOtherSectionsFixed() {
        let c = catalogue(
            row("met", "1", "EUROPE", title: "Landscape", artist: nil),
            row("wmc", "2", "ASIA", title: "Seascape", artist: "Hokusai"),
            row("wmc", "3", "AFRICA", title: "Still Life", artist: "Anon")
        )
        let f = filters(regions: [.europe], subjects: [.landscape])
        // Region chips are asked with Origins lifted, Subjects held at Landscape.
        XCTAssertEqual(c.availableRegions(f, screen: screen, style: style), [.europe])
        XCTAssertEqual(c.availableRegions(filters(subjects: [.seascape]), screen: screen, style: style), [.asia])
        XCTAssertEqual(c.availableSubjects(filters(regions: [.asia]), screen: screen, style: style), [.seascape])
        XCTAssertEqual(c.availableSubjects(filters(), screen: screen, style: style), Set(ArtworkSubject.allCases))
        XCTAssertEqual(c.availableArtists(filters(regions: [.asia]), screen: screen, style: style), ["Hokusai"])
        XCTAssertEqual(c.artists(), ["Anon", "Hokusai"])
        XCTAssertTrue(c.anyMatch(f, screen: screen, style: style))
        XCTAssertFalse(c.anyMatch(filters(regions: [.oceania]), screen: screen, style: style))
    }

    func testArtistsFilterAndFreshInstallDefaults() {
        let c = catalogue(
            row("wmc", "1", "ASIA", title: "A", artist: "Hokusai"),
            row("wmc", "2", "ASIA", title: "B", artist: "Hiroshige")
        )
        XCTAssertEqual(ids(c, filters(artists: ["Hokusai"])), ["1"])
        XCTAssertEqual(Filters.defaults.regions, [.europe, .asia])
        XCTAssertEqual(Filters.defaults.subjects, [.landscape])
        XCTAssertEqual(Filters.defaults.shape, .screen)
        XCTAssertTrue(Filters.defaults.artists.isEmpty)
        XCTAssertFalse(Filters.defaults.hideReligious)
    }

    func testCandidatesShuffleTheSameSet() {
        let rows = (0..<20).map { row("met", "\($0)", "EUROPE", title: "Landscape \($0)") }
        let c = Catalogue(tsv: rows.joined(separator: "\n"))
        let shuffled = c.candidates(filters(), screen: screen, style: style)
        XCTAssertEqual(Set(shuffled.map(\.objectId)), Set(c.entries.map(\.objectId)))
    }
}
