package dev.artwindow

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class CatalogueTest {
    private val screen = Screen(1080, 2340) // aspect ~0.4615

    /**
     * Preferences for a filter test: every section defaults to Any (empty, or
     * [ArtworkShape.ANY] for shape) so a test only has to name the section it cares
     * about — matching the "empty selection means Any" rule [Catalogue.matching]
     * applies, rather than [WallpaperPreferences]'s own constructor defaults, which are
     * the curated Europe+Asia/Landscape a fresh install starts from.
     */
    private fun prefs(
        shape: ArtworkShape = ArtworkShape.ANY,
        regions: Set<ArtworkRegion> = emptySet(),
        subjects: Set<ArtworkSubject> = emptySet(),
        artists: Set<String> = emptySet(),
        hideReligious: Boolean = false,
    ): WallpaperPreferences = WallpaperPreferences(
        artworkShape = shape,
        artworkRegions = regions,
        artworkSubjects = subjects,
        artworkArtists = artists,
        hideReligious = hideReligious,
    )

    /**
     * One TSV row: `source id region width height image_url details_url title byline
     * origin tags [artist]`. [artist] defaults to `null`, producing the eleven-column
     * row every existing museum entry still uses; passing it appends the twelfth
     * column Wikimedia Commons rows add.
     */
    private fun row(
        source: String = "met",
        id: String = "1",
        region: String = "EUROPE",
        width: String = "1080",
        height: String = "2340",
        title: String = "Landscape View", // matches ArtworkSubject.LANDSCAPE by default
        tags: String = "",
        artist: String? = null,
    ): String {
        val fields = mutableListOf(
            source, id, region, width, height,
            "https://example.org/$source-$id.jpg", "https://example.org/d/$source-$id",
            title, "", "", tags,
        )
        artist?.let(fields::add)
        return fields.joinToString("\t")
    }

    /**
     * [count] rows sharing the given traits, ids `prefix-0` … — the pool the floor is
     * measured against needs [Catalogue.MIN_POOL] of them, not one.
     */
    private fun bulk(
        count: Int,
        prefix: String,
        region: String = "EUROPE",
        title: String = "Landscape View",
        width: String = "1080",
        height: String = "2340",
        artist: String? = null,
        source: String = "met",
    ): List<String> = (0 until count).map {
        row(source = source, id = "$prefix-$it", region = region, title = title, width = width, height = height, artist = artist)
    }

    private val pool = Catalogue.MIN_POOL

    @Test
    fun `parse skips comment lines, malformed rows, unknown regions, unknown sources, and bad numbers`() {
        val tsv = listOf(
            "# Generated by catalogue/build.py — this line must be ignored",
            row(id = "1001"),
            row(id = "1002", region = "MARS"), // unknown region
            row(id = "1003", source = "xyz"), // unknown source
            row(id = "1004", width = "not-a-number"),
            row(id = "1005", width = "0"), // not a positive integer
            "not a valid row at all", // wrong field count
        ).joinToString("\n")

        val ids = Catalogue.parse(tsv).candidates(prefs(), screen).map { it.id }

        assertEquals(setOf("1001"), ids.toSet())
    }

    @Test
    fun `every catalogue column round-trips into an Entry`() {
        val tsv = row(source = "nga", id = "436535", region = "EUROPE", title = "Wheat Field", tags = "Landscapes|Nature")
        val entry = Catalogue.parse(tsv)
            .candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE), regions = setOf(ArtworkRegion.EUROPE)), screen)
            .single()

        assertEquals(MuseumSource.NGA, entry.source)
        assertEquals("436535", entry.id)
        assertEquals(ArtworkRegion.EUROPE, entry.region)
        assertEquals(1080, entry.width)
        assertEquals(2340, entry.height)
        assertEquals("https://example.org/nga-436535.jpg", entry.imageUrl)
        assertEquals("https://example.org/d/nga-436535", entry.detailsUrl)
        assertEquals("Wheat Field", entry.title)
        assertEquals(listOf("Landscapes", "Nature"), entry.tags)
        assertEquals("", entry.artist) // the eleven-column format names no artist
    }

    @Test
    fun `a twelfth column is read as the artist, an eleven-column row defaults it to empty`() {
        val withArtist = Catalogue.parse(row(source = "wmc", id = "1", title = "Demon Seated", artist = "Mikhail Vrubel"))
            .candidates(prefs(artists = setOf("Mikhail Vrubel")), screen)
            .single()
        assertEquals("Mikhail Vrubel", withArtist.artist)

        val withoutArtist = Catalogue.parse(row(id = "2"))
            .candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen)
            .single()
        assertEquals("", withoutArtist.artist)
    }

    @Test
    fun `subject queries match a whole word, its plural, and multi-word phrases`() {
        val tsv = listOf(
            row(id = "1", title = "Still Life with Flowers"),
            row(id = "2", title = "Cityscapes at Night"), // "cityscape" + plural "s" folded into LANDSCAPE
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        val stillLife = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.STILL_LIFE)), screen)
        assertEquals(setOf("1"), stillLife.map { it.id }.toSet())

        val landscape = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen)
        assertTrue("2" in landscape.map { it.id })
    }

    @Test
    fun `Danish subject terms from SMK titles are matched like their English counterparts`() {
        val tsv = listOf(
            row(id = "1", source = "smk", title = "Dansk landskab"), // "landskab" -> LANDSCAPE
            row(id = "2", source = "smk", title = "Udsigt over Frederiksborg Slot"), // "udsigt" -> LANDSCAPE
            row(id = "3", source = "smk", title = "Hornbækfiskere på sildefangst", tags = "Havn|Kyst"),
            row(id = "4", source = "smk", title = "Opstilling med blomster"), // -> STILL_LIFE
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        val landscape = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen).map { it.id }
        assertTrue("1" in landscape)
        assertTrue("2" in landscape)

        val seascape = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.SEASCAPE)), screen).map { it.id }
        assertTrue("3" in seascape) // matched on the Danish tags "Havn" (harbour) and "Kyst" (coast)

        val stillLife = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.STILL_LIFE)), screen).map { it.id }
        assertTrue("4" in stillLife)
    }

    @Test
    fun `the English preposition 'by' does not fool the landscape subject`() {
        // Danish "by" (town) is deliberately absent from ArtworkSubject.LANDSCAPE's
        // queries — this is the false positive that ruled it out.
        val tsv = row(id = "1", title = "Chrysanthemums by a Stream")
        val ids = Catalogue.parse(tsv).candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen).map { it.id }
        assertTrue(ids.isEmpty())
    }

    @Test
    fun `a Danish portrait title is excluded the same as an English one`() {
        val tsv = row(id = "1", source = "smk", title = "Mandsportræt", tags = "Landscapes")
        val ids = Catalogue.parse(tsv).candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen).map { it.id }
        assertTrue(ids.isEmpty())
    }

    @Test
    fun `a portrait is excluded by title or by tag even though it matches a subject`() {
        val tsv = listOf(
            row(id = "1", title = "Landscape at Dawn", tags = "Landscapes"),
            row(id = "2", title = "Portrait of a Lady", tags = "Landscapes"),
            row(id = "3", title = "Untitled", tags = "Landscapes|Portraits"),
        ).joinToString("\n")
        val ids = Catalogue.parse(tsv).candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen).map { it.id }

        assertTrue("1" in ids) // an ordinary landscape is unaffected
        assertFalse("2" in ids) // "Portrait" in the title
        assertFalse("3" in ids) // "Portraits" tag
    }

    @Test
    fun `a religious scene is excluded only when hideReligious is set`() {
        val tsv = row(id = "1", title = "The Crucifixion", tags = "Landscapes")
        val catalogue = Catalogue.parse(tsv)

        val shown = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen)
        assertTrue("1" in shown.map { it.id })

        val hidden = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE), hideReligious = true), screen)
        assertTrue(hidden.isEmpty())
    }

    @Test
    fun `an empty section means Any, not nothing`() {
        val tsv = listOf(
            row(id = "1", region = "EUROPE", title = "Landscape at Dawn"),
            row(id = "2", region = "ASIA", title = "Still Life with Flowers"),
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        // Any region, any subject: both entries qualify.
        assertEquals(setOf("1", "2"), catalogue.candidates(prefs(), screen).map { it.id }.toSet())
        // A chosen region still leaves the subject section at Any.
        assertEquals(setOf("1"), catalogue.candidates(prefs(regions = setOf(ArtworkRegion.EUROPE)), screen).map { it.id }.toSet())
    }

    @Test
    fun `sections are ANDed together while options within one section are ORed`() {
        val tsv = listOf(
            row(id = "1", region = "EUROPE", title = "Landscape at Dawn"), // Europe, landscape
            row(id = "2", region = "ASIA", title = "Mountain Landscape"), // Asia, landscape
            row(id = "3", region = "EUROPE", title = "Still Life with Flowers"), // Europe, still life
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        // Two subjects checked (OR within Subjects) narrowed to one region (AND with Origins).
        val ids = catalogue.candidates(
            prefs(regions = setOf(ArtworkRegion.EUROPE), subjects = setOf(ArtworkSubject.LANDSCAPE, ArtworkSubject.STILL_LIFE)),
            screen,
        ).map { it.id }.toSet()
        assertEquals(setOf("1", "3"), ids) // id 2 fails Origins even though it matches Subjects
    }

    @Test
    fun `an entry's exact pixel aspect is checked against the shape preference`() {
        val tsv = listOf(
            row(id = "phone", width = "1080", height = "2340", title = "Phone-shaped Landscape"), // aspect 0.4615
            row(id = "wide", width = "3600", height = "2400", title = "Wide Landscape"), // aspect 1.5, renders fine when enlargement is small
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        val phoneOnly = catalogue.candidates(prefs(shape = ArtworkShape.SCREEN, subjects = setOf(ArtworkSubject.LANDSCAPE)), screen)
        assertEquals(setOf("phone"), phoneOnly.map { it.id }.toSet())

        val anyShape = catalogue.candidates(prefs(subjects = setOf(ArtworkSubject.LANDSCAPE)), screen)
        assertEquals(setOf("phone", "wide"), anyShape.map { it.id }.toSet())
    }

    @Test
    fun `an entry whose aspect fits but whose pixels are too small to render is excluded`() {
        val tsv = listOf(
            row(id = "full-size", width = "1080", height = "2340", title = "Landscape at Dawn"),
            // Same aspect (~0.462) as the screen, but covering it would need over 5x
            // enlargement — past Screen.MAX_ENLARGEMENT — so this can never render.
            row(id = "too-small", width = "200", height = "433", title = "Tiny Landscape"),
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        val ids = catalogue.candidates(prefs(shape = ArtworkShape.SCREEN, subjects = setOf(ArtworkSubject.LANDSCAPE)), screen)
        assertEquals(setOf("full-size"), ids.map { it.id }.toSet())
    }

    @Test
    fun `artists lists distinct non-empty names sorted, ignoring rows with none`() {
        val tsv = listOf(
            row(id = "1", source = "wmc", artist = "Mikhail Vrubel"),
            row(id = "2", source = "wmc", artist = "Ivan Shishkin"),
            row(id = "3", source = "wmc", artist = "Mikhail Vrubel"), // duplicate, counted once
            row(id = "4"), // museum row, no artist column at all
        ).joinToString("\n")

        assertEquals(listOf("Ivan Shishkin", "Mikhail Vrubel"), Catalogue.parse(tsv).artists())
    }

    @Test
    fun `Vrubel with Any subject and Any origin gives only Vrubel`() {
        val tsv = listOf(
            row(id = "1", source = "wmc", title = "Demon Seated", artist = "Mikhail Vrubel"), // matches no subject
            row(id = "2", title = "Landscape at Dawn"), // a landscape, but not by Vrubel
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        val ids = catalogue.candidates(prefs(artists = setOf("Mikhail Vrubel")), screen).map { it.id }.toSet()
        assertEquals(setOf("1"), ids) // id 2 fails the Artists section even though every other section is Any
    }

    @Test
    fun `Vrubel with Landscape gives only Vrubel's landscapes`() {
        val tsv = listOf(
            row(id = "1", source = "wmc", title = "Vrubel's Wooded Landscape", artist = "Mikhail Vrubel"), // both
            row(id = "2", source = "wmc", title = "Demon Seated", artist = "Mikhail Vrubel"), // Vrubel, not a landscape
            row(id = "3", title = "Landscape at Dawn"), // a landscape, not Vrubel
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        val ids = catalogue.candidates(
            prefs(subjects = setOf(ArtworkSubject.LANDSCAPE), artists = setOf("Mikhail Vrubel")),
            screen,
        ).map { it.id }.toSet()
        assertEquals(setOf("1"), ids)
    }

    @Test
    fun `a chosen artist is still subject to subject, portrait and religious, but not region or shape`() {
        val tsv = listOf(
            row(id = "1", source = "wmc", region = "ASIA", title = "Demon Downcast", artist = "Mikhail Vrubel"), // another region: not asked
            row(id = "2", source = "wmc", title = "Portrait of a Lady", artist = "Mikhail Vrubel", tags = "Portraits"), // portrait
            row(id = "3", source = "wmc", title = "The Crucifixion", artist = "Mikhail Vrubel"), // religious, only excluded when asked
            row(id = "4", source = "wmc", title = "Demon Seated", artist = "Mikhail Vrubel"), // passes everything
        ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)
        val vrubelInEurope = prefs(regions = setOf(ArtworkRegion.EUROPE), artists = setOf("Mikhail Vrubel"))

        assertEquals(setOf("1", "3", "4"), catalogue.candidates(vrubelInEurope, screen).map { it.id }.toSet())
        assertEquals(
            setOf("1", "4"),
            catalogue.candidates(vrubelInEurope.copy(hideReligious = true), screen).map { it.id }.toSet(),
        )
    }

    @Test
    fun `hasEnough is false one painting short of the floor and true at it`() {
        val short = Catalogue.parse(bulk(pool - 1, "e").joinToString("\n"))
        val enough = Catalogue.parse(bulk(pool, "e").joinToString("\n"))

        assertFalse(short.hasEnough(prefs(), screen))
        assertEquals(pool - 1, short.matchCount(prefs(), screen))
        assertTrue(enough.hasEnough(prefs(), screen))
        assertFalse(enough.hasEnough(prefs(regions = setOf(ArtworkRegion.ASIA)), screen)) // wrong region: none
        assertEquals(0, enough.matchCount(prefs(regions = setOf(ArtworkRegion.ASIA)), screen))
    }

    @Test
    fun `availableRegions needs the floor, computed against the other sections' staged values`() {
        val tsv = (
            bulk(pool, "e", region = "EUROPE", artist = "Mikhail Vrubel") +
                bulk(pool - 1, "a", region = "ASIA", artist = "Katsushika Hokusai") +
                bulk(pool, "o", region = "OCEANIA")
            ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        // Asia holds one painting too few, so it is hidden even though it is not empty.
        assertEquals(setOf(ArtworkRegion.EUROPE, ArtworkRegion.OCEANIA), catalogue.availableRegions(prefs(), screen))
        // A chosen painter is not asked for a region, so no region is hidden on his account.
        assertEquals(
            ArtworkRegion.entries.toSet(),
            catalogue.availableRegions(prefs(artists = setOf("Mikhail Vrubel")), screen),
        )
    }

    @Test
    fun `availableSubjects needs the floor, computed against the other sections' staged values`() {
        val tsv = (
            bulk(pool, "l", title = "Landscape at Dawn") +
                bulk(pool - 1, "s", region = "ASIA", title = "Seascape at Dusk")
            ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        assertEquals(setOf(ArtworkSubject.LANDSCAPE), catalogue.availableSubjects(prefs(), screen))
        assertEquals(setOf(ArtworkSubject.LANDSCAPE), catalogue.availableSubjects(prefs(regions = setOf(ArtworkRegion.EUROPE)), screen))
        // One more seascape tips it over.
        val more = Catalogue.parse(bulk(pool, "s", region = "ASIA", title = "Seascape at Dusk").joinToString("\n"))
        assertTrue(ArtworkSubject.SEASCAPE in more.availableSubjects(prefs(), screen))
    }

    @Test
    fun `availableSubjects excludes a subject without enough entries close enough for the staged shape`() {
        val wide = Catalogue.parse(bulk(pool, "w", width = "3600", height = "2400", title = "Wide Landscape").joinToString("\n"))

        assertTrue(ArtworkSubject.LANDSCAPE in wide.availableSubjects(prefs(), screen))
        assertFalse(ArtworkSubject.LANDSCAPE in wide.availableSubjects(prefs(shape = ArtworkShape.SCREEN), screen))
    }

    @Test
    fun `availableArtists needs one painting, whatever the region and shape`() {
        val tsv = (
            bulk(3, "v", source = "wmc", region = "EUROPE", width = "3600", height = "2400", title = "Landscape at Dawn", artist = "Mikhail Vrubel") +
                bulk(2, "h", source = "wmc", region = "ASIA", title = "Crucifixion Landscape", artist = "Katsushika Hokusai")
            ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)
        val both = setOf("Mikhail Vrubel", "Katsushika Hokusai")

        // Wide, in another region than the one staged, and only three of them: still available.
        assertEquals(both, catalogue.availableArtists(prefs(regions = setOf(ArtworkRegion.OCEANIA), shape = ArtworkShape.SCREEN), screen))
        assertEquals(setOf("Mikhail Vrubel"), catalogue.availableArtists(prefs(hideReligious = true), screen))
        assertEquals(
            mapOf("Katsushika Hokusai" to ArtistBlock.RELIGIOUS),
            catalogue.artistBlocks(prefs(hideReligious = true), screen),
        )
        assertEquals(
            mapOf("Mikhail Vrubel" to ArtistBlock.SUBJECT, "Katsushika Hokusai" to ArtistBlock.SUBJECT),
            catalogue.artistBlocks(prefs(subjects = setOf(ArtworkSubject.STILL_LIFE)), screen),
        )
    }

    @Test
    fun `one painting is enough with an artist and nineteen is not enough without`() {
        val catalogue = Catalogue.parse((bulk(pool - 1, "e") + bulk(1, "v", source = "wmc", artist = "Mikhail Vrubel")).joinToString("\n"))

        assertTrue(catalogue.hasEnough(prefs(artists = setOf("Mikhail Vrubel")), screen))
        assertFalse(Catalogue.parse(bulk(pool - 1, "e").joinToString("\n")).hasEnough(prefs(), screen))
    }

    @Test
    fun `widened leaves adequate filters alone`() {
        val catalogue = Catalogue.parse(bulk(pool, "e").joinToString("\n"))
        val adequate = prefs(regions = setOf(ArtworkRegion.EUROPE), subjects = setOf(ArtworkSubject.LANDSCAPE))

        assertEquals(adequate, catalogue.widened(adequate, screen))
    }

    @Test
    fun `widened relaxes only the section that must go`() {
        // Plenty of Europe, plenty of landscapes, but Asia holds none: Origins alone is
        // the smallest cure, so Subjects and Content stay as given.
        val catalogue = Catalogue.parse(bulk(pool, "e", title = "Landscape at Dawn").joinToString("\n"))
        val thin = prefs(
            regions = setOf(ArtworkRegion.ASIA),
            subjects = setOf(ArtworkSubject.LANDSCAPE),
            hideReligious = true,
        )

        assertEquals(thin.copy(artworkRegions = emptySet()), catalogue.widened(thin, screen))
    }

    @Test
    fun `widened prefers a single section to a pair, and leaves a chosen artist alone`() {
        val tsv = (
            bulk(pool - 1, "v", source = "wmc", title = "Landscape at Dawn", artist = "Mikhail Vrubel") +
                bulk(pool, "x", title = "Still Life with Flowers")
            ).joinToString("\n")
        val catalogue = Catalogue.parse(tsv)

        // No still life by Vrubel, but one painter's work is enough: dropping Subject cures it,
        // and neither Origins nor the Artist section is touched (Origins is not asked anyway).
        val artistLed = prefs(
            regions = setOf(ArtworkRegion.EUROPE),
            subjects = setOf(ArtworkSubject.STILL_LIFE),
            artists = setOf("Mikhail Vrubel"),
        )
        assertEquals(artistLed.copy(artworkSubjects = emptySet()), catalogue.widened(artistLed, screen))

        // Without the artist the floor is twenty: Origins is the one section that must go.
        val thin = prefs(regions = setOf(ArtworkRegion.ASIA), subjects = setOf(ArtworkSubject.STILL_LIFE))
        assertEquals(thin.copy(artworkRegions = emptySet()), catalogue.widened(thin, screen))

        // A painter with something to show is returned untouched.
        val adequate = prefs(artists = setOf("Mikhail Vrubel"))
        assertEquals(adequate, catalogue.widened(adequate, screen))
    }

    @Test
    fun `widened returns filters nothing can rescue unchanged`() {
        val catalogue = Catalogue.parse(bulk(pool - 1, "e").joinToString("\n"))
        val hopeless = prefs(regions = setOf(ArtworkRegion.ASIA), subjects = setOf(ArtworkSubject.LANDSCAPE))

        assertEquals(hopeless, catalogue.widened(hopeless, screen))
    }

    @Test
    fun `thin filters already applied do not block a change of style`() {
        val catalogue = Catalogue.parse(bulk(pool - 1, "e").joinToString("\n"))
        val applied = prefs(regions = setOf(ArtworkRegion.EUROPE))

        assertFalse(catalogue.hasEnough(applied, screen))
        assertTrue(catalogue.canApply(applied.copy(style = WallpaperStyle.BLUR), applied, screen))
        // Touching the filters brings the floor back.
        assertFalse(catalogue.canApply(applied.copy(hideReligious = true), applied, screen))
    }

    @Test
    fun `a change of filters is appliable only with enough paintings`() {
        val catalogue = Catalogue.parse(bulk(pool, "e").joinToString("\n"))
        val applied = prefs()

        assertTrue(catalogue.canApply(applied.copy(artworkRegions = setOf(ArtworkRegion.EUROPE)), applied, screen))
        assertFalse(catalogue.canApply(applied.copy(artworkRegions = setOf(ArtworkRegion.ASIA)), applied, screen))
    }

    @Test
    fun `paintingsBy counts an artist's paintings and leaves portraits out`() {
        val catalogue = Catalogue.parse(
            (bulk(3, "a", artist = "Tom Roberts") +
                bulk(2, "p", title = "Portrait of a Man", artist = "Tom Roberts") +
                bulk(4, "b", artist = "Conrad Martens")).joinToString("\n"),
        )

        assertEquals(3, catalogue.paintingsBy("Tom Roberts"))
        assertEquals(4, catalogue.paintingsBy("Conrad Martens"))
        assertEquals(0, catalogue.paintingsBy("Nobody"))
    }

    @Test
    fun `the hung size swaps only for a wide painting on a tall screen with rotate on`() {
        val on = prefs().copy(rotateWide = true)

        assertEquals(2400 to 3600, on.hungSize(3600, 2400, screen))
        assertEquals(2400 to 3600, on.hungSize(2400, 3600, screen))
        assertEquals(3600 to 2400, on.hungSize(3600, 2400, Screen(2340, 1080)))
        assertEquals(3600 to 2400, prefs().hungSize(3600, 2400, screen))
    }

    @Test
    fun `with rotate on a wide painting is judged as it will hang`() {
        val catalogue = Catalogue.parse(bulk(pool, "w", width = "5000", height = "2400").joinToString("\n"))
        val phoneShaped = prefs(shape = ArtworkShape.SCREEN)

        assertFalse(catalogue.hasEnough(phoneShaped, screen))
        assertTrue(catalogue.hasEnough(phoneShaped.copy(rotateWide = true), screen))
    }
}
