"""The artist browser's data: one bundled picture and one "about" link per
named painter, written to `catalogue/dist/artists/`.

For every painter whose `artist` column survived `build.MIN_PER_CHOICE`, this
writes `<slug>.jpg` (that painter's `showcase` painting from `artists.json`, at
most `MAX_LONG_SIDE` pixels on the long side) and `index.tsv`, whose columns are
`name region about showcase title byline file`. `name`, `title` and `byline`
are copied from the painter's `showcase` row in the combined rows, so they
agree byte for byte with `paintings.tsv`. A picture whose painter no longer has
a row is deleted. A surviving painter with no `about`, no `showcase`, or a
`showcase` that is not one of their own rows fails the run: nothing here guesses.

`showcase` is `<source>:<id>`, a row of that painter's own. The picture is
downloaded from that row's `image_url` through a paced client and downscaled
here with Pillow, so any museum's image host works; an existing file is kept
unless `refresh` is set.
"""

import json
import os
import re
import unicodedata

from . import http

ARTISTS_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "artists.json")

MAX_LONG_SIDE = 1400

INDEX_COLUMNS = ("name", "region", "about", "showcase", "title", "byline", "file")


def slug(name: str) -> str:
    """`Almeida Júnior` -> `almeida-junior`."""
    folded = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", folded.lower()).strip("-")


def load_artists() -> list[dict]:
    """The curated painters in `artists.json`: `name`, `aliases`, `about`,
    `showcase`."""
    with open(ARTISTS_PATH, encoding="utf-8") as f:
        return json.load(f)


def _entries(rows: list[dict]) -> list[tuple[dict, dict]]:
    """`(artists.json entry, showcase row)` for each painter still named in
    `rows`, sorted by name. Raises `SystemExit` naming the first one that
    cannot be served."""
    by_key = {f"{row['source']}:{row['id']}": row for row in rows}
    named = {row["artist"] for row in rows if row.get("artist")}
    entries = []
    for artist in load_artists():
        name = artist["name"]
        if name not in named:
            continue
        if not artist.get("about"):
            raise SystemExit(f"showcase: {name} keeps an Artist chip but has no \"about\" in artists.json")
        if not artist.get("showcase"):
            raise SystemExit(f"showcase: {name} keeps an Artist chip but has no \"showcase\" in artists.json")
        row = by_key.get(artist["showcase"])
        if row is None or row.get("artist") != name:
            raise SystemExit(
                f"showcase: {name}'s showcase {artist['showcase']!r} is not one of their rows in paintings.tsv"
            )
        entries.append((artist, row))
    return sorted(entries, key=lambda e: e[0]["name"])


def _fetch(client: http.PacedClient, image_url: str, dest: str) -> None:
    try:
        from PIL import Image
    except ImportError:
        raise SystemExit("showcase: Pillow is needed to downscale the pictures (pip3 install pillow)")
    raw = dest + ".download"
    client.download(image_url, raw)
    try:
        with Image.open(raw) as image:
            image = image.convert("RGB")
            image.thumbnail((MAX_LONG_SIDE, MAX_LONG_SIDE), Image.LANCZOS)
            image.save(dest, "JPEG", quality=88, optimize=True)
    finally:
        os.remove(raw)


def write(rows: list[dict], out_dir: str, refresh: bool, host_gaps: dict[str, float]) -> None:
    """`host_gaps` is every source's `HOST_GAPS` merged, so a showcase picture
    is fetched as politely as the catalogue itself was."""
    entries = _entries(rows)
    os.makedirs(out_dir, exist_ok=True)
    client = http.PacedClient(gap_seconds=host_gaps)

    wanted = set()
    index_lines = []
    for artist, row in entries:
        file_name = f"{slug(artist['name'])}.jpg"
        wanted.add(file_name)
        dest = os.path.join(out_dir, file_name)
        if refresh or not os.path.isfile(dest):
            print(f"  showcase: {artist['name']} -> {file_name}", flush=True)
            _fetch(client, row["image_url"], dest)
        fields = [artist["name"], row["region"], artist["about"], artist["showcase"],
                  row["title"], row["byline"], file_name]
        index_lines.append("\t".join(" ".join(f.split()) for f in fields))

    with open(os.path.join(out_dir, "index.tsv"), "w", encoding="utf-8", newline="\n") as f:
        f.write("# Generated by catalogue/build.py (showcase.py) from catalogue/artists.json. Do not edit by hand.\n")
        for line in index_lines:
            f.write(line + "\n")
    for existing in os.listdir(out_dir):
        if existing.endswith(".jpg") and existing not in wanted:
            os.remove(os.path.join(out_dir, existing))
