FROM rust:1.88-bookworm

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        libdbus-1-dev \
        libgtk-3-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
